### ISSUE TITLE
填写到环境变量link，函数配置或config.py均可

### ISSUE THREAD

**Issue by bianwenfei** [Thund1R/daily-info#1]
api网关触发配置在哪？

**Comment by Thund1R** [comment]
刚刚才跟新哦，请再查看教程更新文件并完成配置试试看

**Comment by bianwenfei** [comment]
没搞懂获取了公网地址该补充到哪里
能配张图片嘛填写到环境变量link，函数配置或config.py均可

**Comment by Thund1R** [comment]
已经更新了金山文档－配置页面－关于
填写link的部分截图

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thund1R/daily-info] 填写到环境变量link，函数配置或config.py均可 (Issue #1)




 
没搞懂获取了公网地址该补充到哪里
 能配张图片嘛填写到环境变量link，函数配置或config.py均可

**Comment by bianwenfei** [comment]
在函数配置中修改环境变量出错
![image](https://user-images.githubusercontent.com/73779172/187341718-6f6a2b8e-4001-472c-a412-d56dc644715a.png)

**Comment by Thund1R** [comment]
很遗憾，没遇到过这个问题，抱歉。如果影响严重，建议备份配置信息，新建一个云函数



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 中午11:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Thund1R/daily-info] 填写到环境变量link，函数配置或config.py均可 (Issue #1)




 
在函数配置中修改环境变量出错
