### ISSUE TITLE
get_weather可以增加adm参数直接查询city-county

### ISSUE THREAD

**Issue by leichaoL** [Thund1R/daily-info#2]
可以考虑对`get_weather(city_name)`函数进行修改，`city_url`增加`adm`参数，`city_url = f"https://geoapi.qweather.com/v2/city/lookup?&adm={city}&key={qweather}&location={county}"`，可以直接对`city-county`进行查询，可能会更加方便。
不太会用github提pull，就提个issue吧。

**Comment by Thund1R** [comment]
感谢感谢，帮了大忙，后续更新，因为借鉴的别人的代码没有注意参数
