### ISSUE TITLE
设置的call和content没起作用...

### ISSUE THREAD

**Issue by zhufacai** [Thund1R/daily-info#4]

**Comment by Thund1R** [comment]
一般不会出现这种情况哈，如果是配置在云函数端请检查是不是在函数配置的环境变量里面也填写了，导致call和content没生效

**Comment by zhufacai** [comment]
一开始在云函数环境变量里面填了，后面删掉了，但还是不起作用，另外我在vercel部署的Diary，替换vercel.app为自己的域名了，但是图文详情页还是打不开，点继续访问没反应

**Comment by Thund1R** [comment]
建议把云函数配置备份一下，删掉云函数，重新拉取代码配置。另外已经使用云函数的话建议使用教程里面配置页面的方法二，用云函数的api网关触发器实现link方便快捷得多。vercel.app在国内被ban，即使用自己的域名也会出现很多问题，微信会把中文字符全部截掉，另外我试了试，你的diary并没有部署成功，现在版本的diary已经删除了vercel相关配置

**Comment by zhufacai** [comment]
> 
刚发现确实没部署成功。。。我没注意看直接fork然后导入vercel了😑

**Comment by zhufacai** [comment]
在服务器上重新部署了，call和content还是没生效，换成天行的彩虹屁接口之后index.py执行出错了
`SyntaxError: invalid syntax
failed to compile /www/wwwroot/daily-info/index.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27877)
spawned uWSGI worker 1 (pid: 27879, cores: 2)
spawned uWSGI http 1 (pid: 27880)`

我的index.py配置如下
`def get_my_content():
     my_content = content
     if my_content:
         return my_content
     else:
         try:
             caihong_url = "http://api.tianapi.com/caihongpi/index?key="+"3ea506******1d189dfb"
             caihong_res = requests.get(caihong_url).json()
             caihong_item0 = caihong_res["newslist"][0]["content"]
             caihong_tip = "🌈 " + caihong_item0
             return caihong_tip
         except Exception as e:
             print("获取彩虹屁数据出错:", e)
             return None
`
注释掉了get_my_content这一段
`def get_my_content():
    my_content = content
    if my_content:
        return my_content
    else:
        return None`

**Comment by Thund1R** [comment]
你这个貌似是方法使用错了，服务器上直接python 路径/index.py 或者 python3 路径/index.py，而不是用wsgi去运行它。。。

**Comment by zhufacai** [comment]
我用的宝塔，启动方式选别的都不行，启动之后就自动停止了，只有uwsgi才可以
![image](https://user-images.githubusercontent.com/14821269/189488057-a0c77302-1471-4029-a254-c15e3e34afc6.png)
然后添加了一个shell脚本定时执行index.py
![image](https://user-images.githubusercontent.com/14821269/189488115-0b37a42a-a71d-4839-a26d-491292c895f1.png)
这样不用彩虹屁接口的话可以正常推送消息，只是call和content不起作用，但是换成彩虹屁之后就出错了

**Comment by zhufacai** [comment]
`File "index.py", line 57
    caihong_res = requests.get(caihong_url).json()
    ^
IndentationError: unexpected indent level`
搞不清楚啥情况，先是提示第50行，我看了下第50行因为填了天行的接口所以换行了，我就给敲到一行了，又提示第57行，放弃了。。。

**Comment by Thund1R** [comment]
这个肯定不用项目管理器来启动它，就是设置定时任务执行就好，不需要一直运行它。报错应该是说你的缩进有问题。还是不生效建议重新拉代码

**Comment by zhufacai** [comment]
重新拉了一遍还是不生效😥算了这样也可以了。。。
![4fff7e4d55289a85e73fb10a720cf5f](https://user-images.githubusercontent.com/14821269/189490780-bf4f78a1-c862-40e3-91c4-820629e2e6bd.jpg)

**Comment by zhufacai** [comment]
我刚把推送模式改成单图文后call和content终于生效了。。。

**Comment by Thund1R** [comment]
哈哈哈哈哈给我整麻了，多图文模式下根本就没有空白放call和content，当然只能在单图文下生效

**Comment by zhufacai** [comment]
> 哈哈哈哈哈给我整麻了，多图文模式下根本就没有空白放call和content，当然只能在单图文下生效

麻中麻中麻。。。😓
